enabled: true
mapping:
  user:
    table: m_user
    fields:
      id: id
      fullname: display_name
      username: username
      password: password
      role_id: id_staff_role
    default:
      role_id: 1f3de71e-46ba-46d6-b5a4-5fd2a1afb2b2
  role:
    table: m_staff_role
    fields:
      id: id
      name: name
  session:
    table: t_session
    fields:
      id: id
      status: status
      user_id: id_user
features:
  login: true
  logout: true
  register: true
  reset_password: true
