enabled: true
mapping:
  user:
    table: m_user
    fields:
      id: id
      fullname: display_name
      username: username
      password: password
      role: role
    default:
      role: user
  session:
    table: t_session
    fields:
      id: id
      status: status
      user_id: id_user
features:
  login: true
  logout: true
  register: true
  reset_password: true
